### PR TITLE
Create pr.yml

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by maelle** [comment]
@vsoch I'm surprised that "no URL was collected". Is it because I fed relative paths to the workflow?

**Comment by maelle** [comment]
log https://github.com/r-hub/docs/runs/585900061?check_suite_focus=true

**Comment by maelle** [comment]
I tried with print_all and nothing was printed: https://github.com/r-hub/docs/runs/585930899?check_suite_focus=true so probably no file was found.

**Comment by maelle** [comment]
And for info my goal is to make this job a PR command, not a workflow run on every commit in a PR (i.e. it'd run if in a PR I wrote a comment "/urlcheck", like in https://github.com/tidyverse/ggplot2/blob/master/.github/workflows/pr-commands.yaml -- otherwise URLs could be checked many times in a PR with many commits. This + a monthly check of all links over the repo is enough for my needs (vs being "spammed" by URL checks).

**Comment by vsoch** [comment]
When you need to debug it’s helpful to look at the parameters printed at the beginning:

62C26B10-5401-42BC-BFFD-BBB046ED9047

In this case you want to check a .yml file but it’s not included in your extensions.

**Comment by maelle** [comment]
No I only want to check the md, and it doesn't get checked (I am fine passing the yml but do you mean it creates a bug?)

**Comment by vsoch** [comment]
I suspect it’s also erroring because the file names are in double quotes. In your yaml file you can list the paths in one line, comma separated, no quotes. Yaml does not require quotes unless there is a character that needs it.

**Comment by maelle** [comment]
Thanks, and sorry! I'll unquote the env variable.

**Comment by maelle** [comment]
And I'll submit the workflow as example 😇

**Comment by vsoch** [comment]
@maelle you just gave me a really cool idea - we could have some kind of action / bot that responded to /check-urls (or something like @urlchecker-action check-urls. I've never made a bot before, but I'll note it because it would be cool to have!

**Comment by vsoch** [comment]
@maelle this is awesome - please contribute the recipe to urlchecker-action and also add your repo address in the README to showcase it!

**Comment by maelle** [comment]
Yes will do! Thanks a ton for empowering me!

**Pull request merged**
