### PR TITLE
Implement feedback

### PR DESCRIPTION
**Pull request by ZoeLocke**
New version following project with @maelle.
If testing on a different branch, change editBranch in config.toml to ensure the edit links next to each section work.

### CODE REVIEW

**Comment by ZoeLocke** [comment]
Heading in sidebar fixed
Formatting for links fixed

**Comment by maelle** [comment]
Thanks! The preview is failing.

**Comment by ZoeLocke** [comment]
Can you retry the build @maelle ?

**Comment by maelle** [comment]
@gaborcsardi it seems I can re-trigger a Netlify build, can you?

**Comment by gaborcsardi** [comment]
yep

**Review by maelle — APPROVED** [review]
Thank you!

**Comment by maelle** [comment]
Oh wait what happened to the footer there was at some point in the previews?

**Review by maelle — CHANGES_REQUESTED** [review]
The footer is missing :-)

**Comment by ZoeLocke** [comment]
Removed from the BaseOf for some reason, added back now

**Comment by maelle** [comment]
Thank you! There's something weird going on with the sidebar + footer

image

**Comment by maelle** [comment]
A minor comment: The link for "CRAN source code mirror" should be https://github.com/cran/

**Comment by ZoeLocke** [comment]
Fixed and pushed

**Comment by maelle** [comment]
ok, my only remaining comment is https://github.com/r-hub/docs/pull/28#issuecomment-621953008

**Comment by maelle** [comment]
The TOC doesn't expand in the preview :thinking:

**Comment by ZoeLocke** [comment]
It's working for me @maelle (following the details link in the netlify update)

**Comment by maelle** [comment]
Oooh there has to be some caching, because yeah it works in Chrome / in a private Firefox window.

It looks good to me.

@gaborcsardi any comment?

**Review by maelle — APPROVED** [review]

**Pull request merged**
